@startuml Report Submission
Reporter->>UI: LogIn
UI->>Reporter: Response
UI->>ClientsAPI: Fetch project & client data
ClientsAPI->>UI: 
UI->>ReportAPI: GetListOfProjects()
ReportAPI->>UI: 
Reporter->>UI: SelectReport(id)
UI->>ReportAPI: GetReport(id)
ReportAPI->>UI: ReportDetail
Reporter->>UI: SubmitReport()
UI->>ReportAPI: PostData()
ReportAPI->>ReportAPI: StoreReport
ReportAPI->>MessagingPlatform: RaiseReportSubmittedEvent
ReportAPI->>UI: 
UI->>Reporter: 
MessagingPlatform->>ReportAPI: ReceivedReportSubmittedEvent()
ReportAPI->>UserService: WhoWantsThisReport(highestRisk)
UserService->>ReportAPI: 
ReportAPI->>MessagingPlatform: SendNotification()    
MessagingPlatform->>NotificationService: ReceivedSendNotification
NotificationService->>EmailService: SendAnEmail()
MessagingPlatform->>AuditService: ReceivedReportSubmittedEvent()
AuditService->>AuditService: SaveToAudit()
